### ISSUE TITLE
chkmd: Add default config

### ISSUE THREAD

**Issue by reedobrien** [v-studios/chkmd#1]
Add a default config, so that if no config file is specified we can still run a check. Need to determine what mimetypes are the default.

Config file in repo

**Comment by reedobrien** [comment]
Whoops closed too early.

**Comment by reedobrien** [comment]
This is ready for review.

**Comment by charlescbeebe** [comment]
@reedobrien lgtm.

**Comment by reedobrien** [comment]
Fixes #1 in 9f15e81
