### ISSUE TITLE
chkmd: support all tags from our example/template spreadsheet/md for dummies guide.

### ISSUE THREAD

**Issue by reedobrien** [v-studios/chkmd#2]
We need to implement funcctions to support all the tags we specify in our metadata guide.

 

This would be a function to extract and one to report if that extracted 

Us | IPTC | exiftool
------------ | ------------ | ------------  
NASA ID | Job Identifier or Original Transmission Reference | File Name
Title | Object Name or Headline | Object Name or Headline
508 Description | N/A | N/A
Description | Caption-Abstract | Caption-Abstract	
Date Created | Digital Creation Date + Digital Creation Time | Digital Creation Date + Digital Creation Time or Date/Time Original
Location | City + Country-Primary Location Name | City + Country-Primary Location Name
Keywords	 | Keywords | Keywords
Media Type | N/A | Mime Type split on '/' [0]
File Format | N/A | File Type
Center | N/A | N/A	
Secondary Creator Credit | N/A | N/A	
Photographer | By-line | By-line 	
Album | N/A | N/A

- [x] NASA ID	
- [x] Title	
- [x] ~~508 Description~~
- [x] Description	
- [x] Date Created	
- [x] Location	
- [x] Keywords	
- [x] Media Type	
- [x] File Format	
- [x] ~~Center~~	
- [x] ~~Secondary Creator Credit~~	
- [x] Photographer	
- [x] ~~Album~~

**Comment by reedobrien** [comment]
@shentonfreude these look like the fields you want in the report? N/A would not be available as embedded data. Do we really want to output the abstract? Or just T/F for whether there is data there? Not sure how to actually validate all the data, so prolly won't on this pass.

**Comment by reedobrien** [comment]
This is ready for review.

**Comment by charlescbeebe** [comment]
@reedobrien lgtm.

**Comment by reedobrien** [comment]
Fixed #2 in 555e455
